esphome:
  name: nexa-remote

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Nexa-Remote Fallback Hotspot"
    password: "s7BoFEjZx1bI"

captive_portal:

remote_transmitter:
  pin: GPIO13
  carrier_duty_percent: 100%

web_server:
  port: 80

switch:
  - platform: template
    name: test
    optimistic: true
    turn_on_action:
      - remote_transmitter.transmit_nexa:
          device: 0x38D
          group: 0
          state: 1
          channel: 15
          level: 0
          repeat:
            times: 5
    turn_off_action:
      - remote_transmitter.transmit_nexa:
          device: 0x38D
          group: 0
          state: 0
          channel: 15
          level: 0
          repeat:
            times: 5
