esphome:
  name: smartplug-wifip130fwt
  friendly_name: Smart Plug
  name_add_mac_suffix: true

bk72xx:
  board: generic-bk7231t-qfn32-tuya

web_server:
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:

logger:
captive_portal:
mdns:

binary_sensor:
  - platform: gpio
    id: binary_switch_1
    pin:
      number: P10
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: switch_1
    on_click:
      - min_length: 2s
        max_length: 5s
        then:
          - button.press: restart_btn_1
      - min_length: 6s
        max_length: 10s
        then:
          - button.press: factory_reset_btn_1

switch:
  - platform: gpio
    id: switch_1
    name: Relay 1
    pin: P26
    on_turn_on:
      then:
        - light.turn_on: status_led_1
    on_turn_off:
      then:
        - light.turn_off: status_led_1

button:
  - platform: restart
    id: restart_btn_1
    name: Restart
    entity_category: diagnostic

  - platform: factory_reset
    id: factory_reset_btn_1
    name: Factory Reset
    entity_category: diagnostic

light:
  - platform: status_led
    name: Switch state
    pin:
      number: P6
      inverted: true
    id: status_led_1
    internal: true
    on_state:
      then:

sensor:
  - platform: wifi_signal
    name: WiFi Signal Sensor
    entity_category: diagnostic
