esphome:
  name: smartplug-wifip130fwt
  friendly_name: Smart Plug
  name_add_mac_suffix: true

  project:
    name: smartplug.wifip130fwt
    version: 0.0.1

bk72xx:
  board: generic-bk7231t-qfn32-tuya

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  ap:
    password: !secret ap_password

captive_portal:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

logger:

binary_sensor:
  - platform: gpio
    id: binary_switch_1
    pin:
      number: P10
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: switch_1

switch:
  - platform: gpio
    id: switch_1
    name: Relay 1
    pin: P26

status_led:
  pin:
    number: P6
    inverted: true

sensor:
  - platform: wifi_signal
    name: WiFi Signal Sensor
    entity_category: diagnostic
