esphome:
  name: smartplug-wifip130fwt
  name_add_mac_suffix: true

bk72xx:
  board: generic-bk7231t-qfn32-tuya

web_server:
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

captive_portal:

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  ap:
    password: !secret ap_password
    ap_timeout: 40s

binary_sensor:
  - platform: gpio
    id: binary_switch_1
    pin:
      number: P10
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: switch_1

switch:
  - platform: gpio
    id: switch_1
    name: Relay 1
    pin: P26

status_led:
  pin:
    number: P6
    inverted: true
